// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package wsdl11

case class XDocumentation(mixed: Seq[scalaxb.DataRecord[Any]],
  attributes: Map[String, scalaxb.DataRecord[Any]])

trait XDocumentationOption

trait XDocumented {
  val documentation: Option[wsdl11.XDocumentation]
}


/** 
         This type is extended by  component types
         to allow attributes from other namespaces to be added.
         
*/
trait XOpenAtts {
  val documentation: Option[wsdl11.XDocumentation]
  val attributes: Map[String, scalaxb.DataRecord[Any]]
}


case class XDefinitionsType(documentation: Option[wsdl11.XDocumentation],
  importValue: Seq[wsdl11.XImportType],
  types: Option[wsdl11.XTypesType],
  message: Seq[wsdl11.XMessageType],
  portType: Seq[wsdl11.XPortTypeType],
  binding: Seq[wsdl11.XBindingType],
  service: Seq[wsdl11.XServiceType],
  any: Seq[scalaxb.DataRecord[Any]],
  targetNamespace: Option[java.net.URI] = None,
  name: Option[String] = None) extends XDocumented


case class XImportType(documentation: Option[wsdl11.XDocumentation],
  namespace: java.net.URI,
  location: java.net.URI) extends XDocumented


case class XTypesType(documentation: Option[wsdl11.XDocumentation],
  any: Seq[scalaxb.DataRecord[Any]]) extends XDocumented


case class XMessageType(documentation: Option[wsdl11.XDocumentation],
  part: Seq[wsdl11.XPartType],
  name: String) extends XDocumented


case class XPartType(documentation: Option[wsdl11.XDocumentation],
  name: Option[String] = None,
  typeValue: Option[javax.xml.namespace.QName] = None,
  element: Option[javax.xml.namespace.QName] = None,
  attributes: Map[String, scalaxb.DataRecord[Any]]) extends XOpenAtts


case class XPortTypeType(documentation: Option[wsdl11.XDocumentation],
  operation: Seq[wsdl11.XOperationType],
  name: String) extends XDocumented


case class XOperationType(documentation: Option[wsdl11.XDocumentation],
  xoperationtypeoption: scalaxb.DataRecord[Any],
  name: String) extends XDocumented

trait XOperationTypeOption

case class XParamType(documentation: Option[wsdl11.XDocumentation],
  name: Option[String] = None,
  message: javax.xml.namespace.QName) extends XDocumented


case class XFaultType(documentation: Option[wsdl11.XDocumentation],
  name: String,
  message: javax.xml.namespace.QName) extends XDocumented


trait XStartWithExtensionsTypable extends XDocumented {
  val documentation: Option[wsdl11.XDocumentation]
  val any: Seq[scalaxb.DataRecord[Any]]
}


case class XStartWithExtensionsType(documentation: Option[wsdl11.XDocumentation],
  any: Seq[scalaxb.DataRecord[Any]]) extends XStartWithExtensionsTypable


case class XBindingType(documentation: Option[wsdl11.XDocumentation],
  any: Seq[scalaxb.DataRecord[Any]],
  operation: Seq[wsdl11.XBinding_operationType],
  name: String,
  typeValue: javax.xml.namespace.QName) extends XStartWithExtensionsTypable


case class XFault(documentation: Option[wsdl11.XDocumentation],
  any: Seq[scalaxb.DataRecord[Any]],
  name: String) extends XStartWithExtensionsTypable


case class XBinding_operationType(documentation: Option[wsdl11.XDocumentation],
  any: Seq[scalaxb.DataRecord[Any]],
  input: Option[wsdl11.XStartWithExtensionsTypable],
  output: Option[wsdl11.XStartWithExtensionsTypable],
  fault: Seq[wsdl11.XFault],
  name: String) extends XStartWithExtensionsTypable


case class XServiceType(documentation: Option[wsdl11.XDocumentation],
  port: Seq[wsdl11.XPortType],
  any: Option[scalaxb.DataRecord[Any]],
  name: String) extends XDocumented


case class XPortType(documentation: Option[wsdl11.XDocumentation],
  any: Option[scalaxb.DataRecord[Any]],
  name: String,
  binding: javax.xml.namespace.QName) extends XDocumented

case class XNotificationoperationSequence(output: wsdl11.XParamType)
case class XSolicitresponseoperationSequence(output: wsdl11.XParamType,
  input: wsdl11.XParamType,
  fault: Seq[wsdl11.XFaultType])

case class XRequestresponseoperationSequence(input: wsdl11.XParamType,
  output: wsdl11.XParamType,
  fault: Seq[wsdl11.XFaultType])

case class XOnewayoperationSequence(input: wsdl11.XParamType)
