version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "maven"
    directory: "/mvn-scalaxb"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
