#!/bin/sh
# Build scalaxb and install into the local maven repository.
# (actually just into ~/.m2/repository: it doesn't check settings.xml)
if [ -z "$APPENGINE_SDK_HOME" ] ; then
  echo The APPENGINE_SDK_HOME environment variable must be set.
  exit 1
fi
REPO=$HOME/.m2/repository
cd $(dirname $0)/..
sbt <<EOF
project app
set publishTo := Some(Resolver.file("file",  new File("$REPO")))
publish
EOF
