#!/bin/bash -e
# Build scalaxb and install into a local maven repository.
# By default, installs to ~/.m2/repository.
# Alternatively, a repository path can be specified as an argument.

REPO=${1:-$HOME/.m2/repository}
if [ "$REPO" = "${REPO#/}" ]; then
  REPO=$PWD/$REPO;
fi
cd $(dirname $0)/..
run () { tr '\n' '\000' | xargs -0 sbt; }
run <<EOF
project app
set publishTo := Some(Resolver.file("file",  new File("$REPO")))
publish
EOF
