name: CI
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
            distribution: zulu
            jobtype: 1
          - os: ubuntu-latest
            java: 21
            distribution: corretto
            jobtype: 2
          - os: ubuntu-latest
            java: 17
            distribution: zulu
            jobtype: 3
          - os: ubuntu-latest
            java: 8
            distribution: zulu
            jobtype: 4
    runs-on: ${{ matrix.os }}
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup JVM
      uses: actions/setup-java@v5
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
        cache: 'sbt'
    - uses: sbt/setup-sbt@v1
    - name: Build and test (1)
      if: ${{ matrix.jobtype == 1 }}
      run: |
        sbt -v ++2.12.x "scalaxbPlugin/scripted"
        sbt -v +integration/test
    - name: Build and test (2)
      if: ${{ matrix.jobtype == 2 }}
      shell: bash
      run: |
        sbt -v ++2.12.x "project scalaxbPlugin" "set pluginCrossBuild / sbtVersion := sbtVersion.value" "scripted"
    - name: Build and test (3)
      if: ${{ matrix.jobtype == 3 }}
      shell: bash
      run: |
        sbt -v ++3.x "app/Test/compile" "scalaxbPlugin/scripted"
    - name: Build and test (4)
      if: ${{ matrix.jobtype == 4 }}
      shell: bash
      run: |
        cd mvn-scalaxb
        mvn test
